name: Render and Deploy pkgdown Website
'on': push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
      # use several steps instead of build_site() because I don't want build_reference()
      - name: Build pkgdown
        run: |
           PATH=$PATH:$HOME/bin/ Rscript -e 'pkgdown::init_site(".")'
           PATH=$PATH:$HOME/bin/ Rscript -e 'pkgdown::build_home(".")'
           PATH=$PATH:$HOME/bin/ Rscript -e 'pkgdown::build_articles(".")'
           PATH=$PATH:$HOME/bin/ Rscript -e 'pkgdown::build_news(".")'
           Rscript -e 'rmarkdown::render(input="vignettes/session_lecture.Rmd", output_format = "beamer_presentation", output_file = "../docs/articles/session_lecture.pdf")'
      # deploy needs rsync? Seems so.
      - name: Install deploy dependencies
        run: |
          apt-get update
          apt-get -y install rsync
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
    container: rocker/verse:latest
